---
apiVersion: compositions.io/v1alpha1
kind: Instance
metadata:
  name: sample-crossplane-ec2
  namespace: crossplane-test
spec:
  parameters:
    region: us-east-1
    ami: ami-06aa3f7caf3a30282
    instanceType: t2.micro
    keyName: cplane-keypair2
  compositionRef:
    name: ec2-instance
